#!/usr/bin/env php
<?php

use Maslosoft\Zamm\Application\Application;
use Maslosoft\Zamm\Zamm;

date_default_timezone_set('UTC');

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require_once(__DIR__.'/vendor/autoload.php');
} elseif (file_exists(__DIR__.'/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
}

$app = new Application(new Zamm());
$app->run();
